# requireed environment variables
GOOGLE_PRIVATE_KEY = ENV.fetch("GOOGLE_PRIVATE_KEY")
GOOGLE_CLIENT_EMAIL = ENV.fetch("GOOGLE_CLIENT_EMAIL")
FIREBASE_PROJECT_ID = ENV.fetch("FIREBASE_PROJECT_ID")
LOOTCRATE_DATABASE_URL = ENV.fetch("LOOTCRATE_DATABASE_URL")
FIREBASE_CLOUD_MESSAGING_SERVER_KEY = ENV.fetch("FIREBASE_CLOUD_MESSAGING_SERVER_KEY")